// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_vCTADYJClpa8q2w2-n3basOzBTuXBE',
    appId: '1:516433936980:web:3eacf333810dbfe699e3c1',
    messagingSenderId: '516433936980',
    projectId: 'lab-11-52f6f',
    authDomain: 'lab-11-52f6f.firebaseapp.com',
    storageBucket: 'lab-11-52f6f.appspot.com',
    measurementId: 'G-0S2KTSWV6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_mK82aSzNzHuwr2PIAjq6gCVPFSTSws',
    appId: '1:516433936980:android:adec6fd651cff15199e3c1',
    messagingSenderId: '516433936980',
    projectId: 'lab-11-52f6f',
    storageBucket: 'lab-11-52f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3OFenI0clXoK0z7eVdKpBCmvWi0AKY8',
    appId: '1:516433936980:ios:65fe7f06a87eeb6999e3c1',
    messagingSenderId: '516433936980',
    projectId: 'lab-11-52f6f',
    storageBucket: 'lab-11-52f6f.appspot.com',
    iosBundleId: 'com.example.lab122',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3OFenI0clXoK0z7eVdKpBCmvWi0AKY8',
    appId: '1:516433936980:ios:456771002100ad2999e3c1',
    messagingSenderId: '516433936980',
    projectId: 'lab-11-52f6f',
    storageBucket: 'lab-11-52f6f.appspot.com',
    iosBundleId: 'com.example.lab122.RunnerTests',
  );
}
